# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nullstack Tests

on:
  pull_request:
    branches: [ master, next ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      # cache the dependencies from any node_modules directory
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/pnpm-lock.yaml
          key: node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and link main deps
        run: |
          pnpm install
          pnpm link --global

      - name: Install deps at tests folder
        working-directory: ./tests
        run: |
          pnpm link nullstack --global
          pnpm install

      - name: Run tests
        working-directory: ./tests
        run: pnpm test