# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nullstack Tests

on:
  pull_request:
    branches: [ master, next ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true

    strategy:
      matrix:
        node-version: [12.20.0, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # cache the dependencies from any node_modules directory
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install and link dependencies
        run: npm install
        run: npm link
        run: cd tests
        run: npm link nullstack
        run: npm install

      - name: Run tests
      - run: npm test
